keymap:
- name: App Bindings
  remap:
    super-a:
      remap:
        t:
          launch: ["kitty"]
        w:
          launch: ["firefox"]
        c:
          launch: ["gnome-calculator"]
        f:
          launch: ["nautilus"]
